import { google } from "googleapis";

// Each API may support multiple versions. With this sample, we're getting
// v3 of the youtube API, and using an API key to authenti3ate.
const youtubeClient = google.youtube({
    version: 'v3',
    auth: 'YOUR API KEY'
});

console.log({ google });

export { youtubeClient };

// {
//     google: GoogleApis {
//       abusiveexperiencereport: [Function: abusiveexperiencereport],
//       acceleratedmobilepageurl: [Function: acceleratedmobilepageurl],
//       accessapproval: [Function: accessapproval],
//       accesscontextmanager: [Function: accesscontextmanager],
//       acmedns: [Function: acmedns],
//       addressvalidation: [Function: addressvalidation],
//       adexchangebuyer: [Function: adexchangebuyer],
//       adexchangebuyer2: [Function: adexchangebuyer2],
//       adexperiencereport: [Function: adexperiencereport],
//       admin: [Function: admin],
//       admob: [Function: admob],
//       adsense: [Function: adsense],
//       adsensehost: [Function: adsensehost],
//       advisorynotifications: [Function: advisorynotifications],
//       aiplatform: [Function: aiplatform],
//       alertcenter: [Function: alertcenter],
//       alloydb: [Function: alloydb],
//       analytics: [Function: analytics],
//       analyticsadmin: [Function: analyticsadmin],
//       analyticsdata: [Function: analyticsdata],
//       analyticshub: [Function: analyticshub],
//       analyticsreporting: [Function: analyticsreporting],
//       androiddeviceprovisioning: [Function: androiddeviceprovisioning],
//       androidenterprise: [Function: androidenterprise],
//       androidmanagement: [Function: androidmanagement],
//       androidpublisher: [Function: androidpublisher],
//       apigateway: [Function: apigateway],
//       apigeeregistry: [Function: apigeeregistry],
//       apikeys: [Function: apikeys],
//       appengine: [Function: appengine],
//       apphub: [Function: apphub],
//       appsactivity: [Function: appsactivity],
//       area120tables: [Function: area120tables],
//       artifactregistry: [Function: artifactregistry],
//       assuredworkloads: [Function: assuredworkloads],
//       authorizedbuyersmarketplace: [Function: authorizedbuyersmarketplace],
//       backupdr: [Function: backupdr],
//       baremetalsolution: [Function: baremetalsolution],
//       batch: [Function: batch],
//       beyondcorp: [Function: beyondcorp],
//       biglake: [Function: biglake],
//       bigquery: [Function: bigquery],
//       bigqueryconnection: [Function: bigqueryconnection],
//       bigquerydatapolicy: [Function: bigquerydatapolicy],
//       bigquerydatatransfer: [Function: bigquerydatatransfer],
//       bigqueryreservation: [Function: bigqueryreservation],
//       bigtableadmin: [Function: bigtableadmin],
//       billingbudgets: [Function: billingbudgets],
//       binaryauthorization: [Function: binaryauthorization],
//       blockchainnodeengine: [Function: blockchainnodeengine],
//       blogger: [Function: blogger],
//       books: [Function: books],
//       businessprofileperformance: [Function: businessprofileperformance],
//       calendar: [Function: calendar],
//       certificatemanager: [Function: certificatemanager],
//       chat: [Function: chat],
//       checks: [Function: checks],
//       chromemanagement: [Function: chromemanagement],
//       chromepolicy: [Function: chromepolicy],
//       chromeuxreport: [Function: chromeuxreport],
//       civicinfo: [Function: civicinfo],
//       classroom: [Function: classroom],
//       cloudasset: [Function: cloudasset],
//       cloudbilling: [Function: cloudbilling],
//       cloudbuild: [Function: cloudbuild],
//       cloudchannel: [Function: cloudchannel],
//       cloudcontrolspartner: [Function: cloudcontrolspartner],
//       clouddebugger: [Function: clouddebugger],
//       clouddeploy: [Function: clouddeploy],
//       clouderrorreporting: [Function: clouderrorreporting],
//       cloudfunctions: [Function: cloudfunctions],
//       cloudidentity: [Function: cloudidentity],
//       cloudiot: [Function: cloudiot],
//       cloudkms: [Function: cloudkms],
//       cloudprofiler: [Function: cloudprofiler],
//       cloudresourcemanager: [Function: cloudresourcemanager],
//       cloudscheduler: [Function: cloudscheduler],
//       cloudsearch: [Function: cloudsearch],
//       cloudshell: [Function: cloudshell],
//       cloudsupport: [Function: cloudsupport],
//       cloudtasks: [Function: cloudtasks],
//       cloudtrace: [Function: cloudtrace],
//       composer: [Function: composer],
//       compute: [Function: compute],
//       config: [Function: config],
//       connectors: [Function: connectors],
//       contactcenteraiplatform: [Function: contactcenteraiplatform],
//       contactcenterinsights: [Function: contactcenterinsights],
//       container: [Function: container],
//       containeranalysis: [Function: containeranalysis],
//       content: [Function: content],
//       contentwarehouse: [Function: contentwarehouse],
//       customsearch: [Function: customsearch],
//       datacatalog: [Function: datacatalog],
//       dataflow: [Function: dataflow],
//       dataform: [Function: dataform],
//       datafusion: [Function: datafusion],
//       datalabeling: [Function: datalabeling],
//       datalineage: [Function: datalineage],
//       datamigration: [Function: datamigration],
//       datapipelines: [Function: datapipelines],
//       dataplex: [Function: dataplex],
//       dataportability: [Function: dataportability],
//       dataproc: [Function: dataproc],
//       datastore: [Function: datastore],
//       datastream: [Function: datastream],
//       deploymentmanager: [Function: deploymentmanager],
//       developerconnect: [Function: developerconnect],
//       dfareporting: [Function: dfareporting],
//       dialogflow: [Function: dialogflow],
//       digitalassetlinks: [Function: digitalassetlinks],
//       discovery: [Function: discovery],
//       discoveryengine: [Function: discoveryengine],
//       displayvideo: [Function: displayvideo],
//       dlp: [Function: dlp],
//       dns: [Function: dns],
//       docs: [Function: docs],
//       documentai: [Function: documentai],
//       domains: [Function: domains],
//       domainsrdap: [Function: domainsrdap],
//       doubleclickbidmanager: [Function: doubleclickbidmanager],
//       doubleclicksearch: [Function: doubleclicksearch],
//       drive: [Function: drive],
//       driveactivity: [Function: driveactivity],
//       drivelabels: [Function: drivelabels],
//       essentialcontacts: [Function: essentialcontacts],
//       eventarc: [Function: eventarc],
//       factchecktools: [Function: factchecktools],
//       fcm: [Function: fcm],
//       fcmdata: [Function: fcmdata],
//       file: [Function: file],
//       firebase: [Function: firebase],
//       firebaseappcheck: [Function: firebaseappcheck],
//       firebaseappdistribution: [Function: firebaseappdistribution],
//       firebasedatabase: [Function: firebasedatabase],
//       firebasedynamiclinks: [Function: firebasedynamiclinks],
//       firebasehosting: [Function: firebasehosting],
//       firebaseml: [Function: firebaseml],
//       firebaserules: [Function: firebaserules],
//       firebasestorage: [Function: firebasestorage],
//       firestore: [Function: firestore],
//       fitness: [Function: fitness],
//       forms: [Function: forms],
//       games: [Function: games],
//       gamesConfiguration: [Function: gamesConfiguration],
//       gamesManagement: [Function: gamesManagement],
//       gameservices: [Function: gameservices],
//       genomics: [Function: genomics],
//       gkebackup: [Function: gkebackup],
//       gkehub: [Function: gkehub],
//       gkeonprem: [Function: gkeonprem],
//       gmail: [Function: gmail],
//       gmailpostmastertools: [Function: gmailpostmastertools],
//       groupsmigration: [Function: groupsmigration],
//       groupssettings: [Function: groupssettings],
//       healthcare: [Function: healthcare],
//       homegraph: [Function: homegraph],
//       iam: [Function: iam],
//       iamcredentials: [Function: iamcredentials],
//       iap: [Function: iap],
//       ideahub: [Function: ideahub],
//       identitytoolkit: [Function: identitytoolkit],
//       ids: [Function: ids],
//       indexing: [Function: indexing],
//       integrations: [Function: integrations],
//       jobs: [Function: jobs],
//       kgsearch: [Function: kgsearch],
//       kmsinventory: [Function: kmsinventory],
//       language: [Function: language],
//       libraryagent: [Function: libraryagent],
//       licensing: [Function: licensing],
//       lifesciences: [Function: lifesciences],
//       localservices: [Function: localservices],
//       logging: [Function: logging],
//       looker: [Function: looker],
//       managedidentities: [Function: managedidentities],
//       manufacturers: [Function: manufacturers],
//       marketingplatformadmin: [Function: marketingplatformadmin],
//       memcache: [Function: memcache],
//       metastore: [Function: metastore],
//       migrationcenter: [Function: migrationcenter],
//       ml: [Function: ml],
//       monitoring: [Function: monitoring],
//       mybusinessaccountmanagement: [Function: mybusinessaccountmanagement],
//       mybusinessbusinesscalls: [Function: mybusinessbusinesscalls],
//       mybusinessbusinessinformation: [Function: mybusinessbusinessinformation],
//       mybusinesslodging: [Function: mybusinesslodging],
//       mybusinessnotifications: [Function: mybusinessnotifications],
//       mybusinessplaceactions: [Function: mybusinessplaceactions],
//       mybusinessqanda: [Function: mybusinessqanda],
//       mybusinessverifications: [Function: mybusinessverifications],
//       networkconnectivity: [Function: networkconnectivity],
//       networkmanagement: [Function: networkmanagement],
//       networksecurity: [Function: networksecurity],
//       networkservices: [Function: networkservices],
//       notebooks: [Function: notebooks],
//       oauth2: [Function: oauth2],
//       ondemandscanning: [Function: ondemandscanning],
//       orgpolicy: [Function: orgpolicy],
//       osconfig: [Function: osconfig],
//       oslogin: [Function: oslogin],
//       pagespeedonline: [Function: pagespeedonline],
//       paymentsresellersubscription: [Function: paymentsresellersubscription],
//       people: [Function: people],
//       places: [Function: places],
//       playablelocations: [Function: playablelocations],
//       playcustomapp: [Function: playcustomapp],
//       playdeveloperreporting: [Function: playdeveloperreporting],
//       playgrouping: [Function: playgrouping],
//       playintegrity: [Function: playintegrity],
//       plus: [Function: plus],
//       policyanalyzer: [Function: policyanalyzer],
//       policysimulator: [Function: policysimulator],
//       policytroubleshooter: [Function: policytroubleshooter],
//       poly: [Function: poly],
//       privateca: [Function: privateca],
//       prod_tt_sasportal: [Function: prod_tt_sasportal],
//       publicca: [Function: publicca],
//       pubsub: [Function: pubsub],
//       pubsublite: [Function: pubsublite],
//       rapidmigrationassessment: [Function: rapidmigrationassessment],
//       readerrevenuesubscriptionlinking: [Function: readerrevenuesubscriptionlinking],
//       realtimebidding: [Function: realtimebidding],
//       recaptchaenterprise: [Function: recaptchaenterprise],
//       recommendationengine: [Function: recommendationengine],
//       recommender: [Function: recommender],
//       redis: [Function: redis],
//       remotebuildexecution: [Function: remotebuildexecution],
//       reseller: [Function: reseller],
//       resourcesettings: [Function: resourcesettings],
//       retail: [Function: retail],
//       run: [Function: run],
//       runtimeconfig: [Function: runtimeconfig],
//       safebrowsing: [Function: safebrowsing],
//       sasportal: [Function: sasportal],
//       script: [Function: script],
//       searchads360: [Function: searchads360],
//       searchconsole: [Function: searchconsole],
//       secretmanager: [Function: secretmanager],
//       securitycenter: [Function: securitycenter],
//       serviceconsumermanagement: [Function: serviceconsumermanagement],
//       servicecontrol: [Function: servicecontrol],
//       servicedirectory: [Function: servicedirectory],
//       servicemanagement: [Function: servicemanagement],
//       servicenetworking: [Function: servicenetworking],
//       serviceusage: [Function: serviceusage],
//       sheets: [Function: sheets],
//       siteVerification: [Function: siteVerification],
//       slides: [Function: slides],
//       smartdevicemanagement: [Function: smartdevicemanagement],
//       solar: [Function: solar],
//       sourcerepo: [Function: sourcerepo],
//       spanner: [Function: spanner],
//       speech: [Function: speech],
//       sql: [Function: sql],
//       sqladmin: [Function: sqladmin],
//       storage: [Function: storage],
//       storagetransfer: [Function: storagetransfer],
//       streetviewpublish: [Function: streetviewpublish],
//       sts: [Function: sts],
//       tagmanager: [Function: tagmanager],
//       tasks: [Function: tasks],
//       testing: [Function: testing],
//       texttospeech: [Function: texttospeech],
//       toolresults: [Function: toolresults],
//       tpu: [Function: tpu],
//       trafficdirector: [Function: trafficdirector],
//       transcoder: [Function: transcoder],
//       translate: [Function: translate],
//       travelimpactmodel: [Function: travelimpactmodel],
//       vault: [Function: vault],
//       vectortile: [Function: vectortile],
//       verifiedaccess: [Function: verifiedaccess],
//       versionhistory: [Function: versionhistory],
//       videointelligence: [Function: videointelligence],
//       vision: [Function: vision],
//       vmmigration: [Function: vmmigration],
//       vmwareengine: [Function: vmwareengine],
//       vpcaccess: [Function: vpcaccess],
//       walletobjects: [Function: walletobjects],
//       webfonts: [Function: webfonts],
//       webmasters: [Function: webmasters],
//       webrisk: [Function: webrisk],
//       websecurityscanner: [Function: websecurityscanner],
//       workflowexecutions: [Function: workflowexecutions],
//       workflows: [Function: workflows],
//       workloadmanager: [Function: workloadmanager],
//       workspaceevents: [Function: workspaceevents],
//       workstations: [Function: workstations],
//       youtube: [Function: youtube],
//       youtubeAnalytics: [Function: youtubeAnalytics],
//       youtubereporting: [Function: youtubereporting],
//       _discovery: Discovery {
//         transporter: [Object ...],
//         options: [Object ...],
//         makeEndpoint: [Function: makeEndpoint],
//         log: [Function: log],
//         discoverAllAPIs: [Function: discoverAllAPIs],
//         discoverAPI: [Function: discoverAPI]
//       },
//       auth: AuthPlus {
//         checkIsGCE: undefined,
//         jsonContent: null,
//         cachedCredential: null,
//         clientOptions: [Object ...],
//         _cachedProjectId: null,
//         keyFilename: undefined,
//         scopes: undefined,
//         JWT: [class JWT],
//         Compute: [class Compute],
//         OAuth2: [class OAuth2Client],
//         GoogleAuth: [class GoogleAuth],
//         AwsClient: [class AwsClient],
//         IdentityPoolClient: [class IdentityPoolClient],
//         ExternalAccountClient: [class ExternalAccountClient],
//         getClient: [Function: getClient],
//         getProjectId: [Function: getProjectId],
//         isGCE: [Getter],
//         setGapicJWTValues: [Function: setGapicJWTValues],
//         getProjectIdOptional: [Function: getProjectIdOptional],
//         findAndCacheProjectId: [Function: findAndCacheProjectId],
//         getProjectIdAsync: [Function: getProjectIdAsync],
//         getUniverseDomainFromMetadataServer: [Function: getUniverseDomainFromMetadataServer],
//         getUniverseDomain: [Function: getUniverseDomain],
//         getAnyScopes: [Function: getAnyScopes],
//         getApplicationDefault: [Function: getApplicationDefault],
//         getApplicationDefaultAsync: [Function: getApplicationDefaultAsync],
//         prepareAndCacheADC: [Function: prepareAndCacheADC],
//         _checkIsGCE: [Function: _checkIsGCE],
//         _tryGetApplicationCredentialsFromEnvironmentVariable: [Function: _tryGetApplicationCredentialsFromEnvironmentVariable],
//         _tryGetApplicationCredentialsFromWellKnownFile: [Function: _tryGetApplicationCredentialsFromWellKnownFile],
//         _getApplicationCredentialsFromFilePath: [Function: _getApplicationCredentialsFromFilePath],
//         fromImpersonatedJSON: [Function: fromImpersonatedJSON],
//         fromJSON: [Function: fromJSON],
//         _cacheClientFromJSON: [Function: _cacheClientFromJSON],
//         fromStream: [Function: fromStream],
//         fromStreamAsync: [Function: fromStreamAsync],
//         fromAPIKey: [Function: fromAPIKey],
//         _isWindows: [Function: _isWindows],
//         getDefaultServiceProjectId: [Function: getDefaultServiceProjectId],
//         getProductionProjectId: [Function: getProductionProjectId],
//         getFileProjectId: [Function: getFileProjectId],
//         getExternalAccountClientProjectId: [Function: getExternalAccountClientProjectId],
//         getGCEProjectId: [Function: getGCEProjectId],
//         getCredentials: [Function: getCredentials],
//         getCredentialsAsync: [Function: getCredentialsAsync],
//         getIdTokenClient: [Function: getIdTokenClient],
//         getAccessToken: [Function: getAccessToken],
//         getRequestHeaders: [Function: getRequestHeaders],
//         authorizeRequest: [Function: authorizeRequest],
//         request: [Function: request],
//         getEnv: [Function: getEnv],
//         sign: [Function: sign],
//         signBlob: [Function: signBlob]
//       },
//       _options: {},
//       getSupportedAPIs: [Function: getSupportedAPIs],
//       options: [Function: options],
//       addAPIs: [Function: addAPIs],
//       discover: [Function: discover],
//       discoverAsync: [Function: discoverAsync],
//       discoverAPI: [Function: discoverAPI]
//     }
//   }
  

// {
//     youtubeClient: Youtube {
//       context: {
//         _options: [Object ...],
//         google: [Object ...]
//       },
//       abuseReports: Resource$Abusereports {
//         context: [Object ...],
//         insert: [Function: insert]
//       },
//       activities: Resource$Activities {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       captions: Resource$Captions {
//         context: [Object ...],
//         delete: [Function: delete],
//         download: [Function: download],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       channelBanners: Resource$Channelbanners {
//         context: [Object ...],
//         insert: [Function: insert]
//       },
//       channels: Resource$Channels {
//         context: [Object ...],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       channelSections: Resource$Channelsections {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       comments: Resource$Comments {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         markAsSpam: [Function: markAsSpam],
//         setModerationStatus: [Function: setModerationStatus],
//         update: [Function: update]
//       },
//       commentThreads: Resource$Commentthreads {
//         context: [Object ...],
//         insert: [Function: insert],
//         list: [Function: list]
//       },
//       i18nLanguages: Resource$I18nlanguages {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       i18nRegions: Resource$I18nregions {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       liveBroadcasts: Resource$Livebroadcasts {
//         context: [Object ...],
//         bind: [Function: bind],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         insertCuepoint: [Function: insertCuepoint],
//         list: [Function: list],
//         transition: [Function: transition],
//         update: [Function: update]
//       },
//       liveChatBans: Resource$Livechatbans {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert]
//       },
//       liveChatMessages: Resource$Livechatmessages {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         transition: [Function: transition]
//       },
//       liveChatModerators: Resource$Livechatmoderators {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list]
//       },
//       liveStreams: Resource$Livestreams {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       members: Resource$Members {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       membershipsLevels: Resource$Membershipslevels {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       playlistImages: Resource$Playlistimages {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       playlistItems: Resource$Playlistitems {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       playlists: Resource$Playlists {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       search: Resource$Search {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       subscriptions: Resource$Subscriptions {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list]
//       },
//       superChatEvents: Resource$Superchatevents {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       tests: Resource$Tests {
//         context: [Object ...],
//         insert: [Function: insert]
//       },
//       thirdPartyLinks: Resource$Thirdpartylinks {
//         context: [Object ...],
//         delete: [Function: delete],
//         insert: [Function: insert],
//         list: [Function: list],
//         update: [Function: update]
//       },
//       thumbnails: Resource$Thumbnails {
//         context: [Object ...],
//         set: [Function: set]
//       },
//       videoAbuseReportReasons: Resource$Videoabusereportreasons {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       videoCategories: Resource$Videocategories {
//         context: [Object ...],
//         list: [Function: list]
//       },
//       videos: Resource$Videos {
//         context: [Object ...],
//         delete: [Function: delete],
//         getRating: [Function: getRating],
//         insert: [Function: insert],
//         list: [Function: list],
//         rate: [Function: rate],
//         reportAbuse: [Function: reportAbuse],
//         update: [Function: update]
//       },
//       watermarks: Resource$Watermarks {
//         context: [Object ...],
//         set: [Function: set],
//         unset: [Function: unset]
//       },
//       youtube: Resource$Youtube {
//         context: [Object ...],
//         v3: [Object ...]
//       }
//     }
//   }
  